### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by brmurdock** [melexis/SENTAnalyzer#10]
First off, THANK YOU!!! your work on this is much appreciated! 

I am trying to get this Analyzer working and keep running into a crash. 
If I open the attached file and run the SENT Analyzer on it with tick time of 3 then change to 6 it decodes the message correctly. If I go straight to tick time of 6, Logic crashes.

[SENT EVERY SECOND.zip](https://github.com/melexis/SENTAnalyzer/files/1713075/SENT.EVERY.SECOND.zip)

**Comment by bavovanachte** [comment]
Hi,

You're very welcome. As you've noticed the analyzer isn't quite mature yet.

I was able to reproduce your issue, thanks for reporting. For completeness, could you say which OS you are using? I was able to reproduce on linux-64, but don't have immediate access to a windows machine to see if the issue occurs on that OS as well.

I'll try to contact the Salaea devs to see if they can help with this. I'll have to understand what happens under the hood when switching configuration vs loading the right configuration when instantiating the analyzer.

**Comment by bavovanachte** [comment]
No error log was generated on the crash (no new files in the Errors folders)

However, when starting the logic analyzer from the command line, I got the following output:

```
Root Path: /home/bvn/Tools/Logic_1_2_14  [ /home/build/ob_logic/Source/Environment.cpp; Environment; 158 ]
Writeable Root Path: /home/bvn/Tools/Logic_1_2_14  [ /home/build/ob_logic/Source/Environment.cpp; Environment; 185 ]
Temp Folder path: /tmp  [ /home/build/ob_logic/Source/Environment.cpp; Environment; 191 ]
Release Mode; analyzer path is /home/bvn/Tools/Logic_1_2_14/Analyzers  [ /home/build/ob_logic/Source/Environment.cpp; Environment; 201 ]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
qt.network.ssl: QSslSocket: cannot resolve SSLv2_client_method
qt.network.ssl: QSslSocket: cannot resolve SSLv2_server_method
First device connected. Creating Primary Display.  [ /home/build/ob_logic/Source/LogicWindow_Devices.cpp; AttachedDevicesChangedSlot; 70 ]
GeneratePixmapEllipses: 1.005660 seconds  [ /home/build/ob_logic/Source/AnalogDisplayEngine.cpp; AnalogDisplayEngine; 38 ]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
device change has triggered sprucing up the empty capture tab.  [ /home/build/ob_logic/Source/LogicWindow_Controller.cpp; ActiveDeviceChanged; 454 ]
setting PrimaryDisplay's Session to NULL.  [ /home/build/ob_logic/Source/PrimaryDisplay.cpp; SetSession; 562 ]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
 Old Bit Collection Constructor Called. this is only for loading sessions.  [ /home/build/ob_logic/Source/BitCollection.cpp; BitCollection; 630 ]
setting PrimaryDisplay's Session to a valid session, 1  [ /home/build/ob_logic/Source/PrimaryDisplay.cpp; SetSession; 564 ]
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
SQL error: no such table: SEARCH_RESULTS1
  [ /home/build/ob_logic/Source/ApiServer.cpp; DeleteTempResultsForAnalyzer; 2733 ]
SQL error: no such table: SEARCH_RESULTS1
  [ /home/build/ob_logic/Source/ApiServer.cpp; DropSearchresults; 2786 ]
CREATE TABLE SEARCH_RESULTS1 AS  SELECT * FROM (  SELECT DUMMY_FRAME_ID, START_TIME, FRAMEID, ANALYZERID, ASCII_DISP AS RESULTS from ANALYZER_RESULTS1 WHERE ANALYZERID = 1 AND START_TIME <= 0 AND ASCII_DISP LIKE '%%' ESCAPE '/' LIMIT 50  ) ORDER BY DUMMY_FRAME_ID;
Segmentation fault (core dumped)
```

**Comment by bavovanachte** [comment]
Created a question in the forums here: https://support.saleae.com/hc/en-us/community/posts/360000647166-Segmentation-fault-on-custom-analyzer

**Comment by Marcus10110** [comment]
I've just attached GDB on Linux and reproduced the crash. It's clear that the problem is here:
https://github.com/melexis/SENTAnalyzer/blob/master/source/SENTAnalyzer.cpp#L124
Specifically, that function is getting called when `framelist` is empty.

I don't know how SENT or this analyzer works, but wrapping that line with `if( framelist.size() > 0 )` seems to fix it.

The reason it works with the above workaround is actually a bug in the analyzer. All data members of the `SENTAnalyzer` class should be cleared at the top of the `SENTAnalyzer::WorkerThread` function. This is because the analyzer will simply get restarted if the user edits any of the analyzer settings. This causes the same instance of the analyzer to get used more than once. 

Note that other actions, such as removing and then re-adding an analyzer, or starting another capture while the analyzer is still attached to the capture tab session will still trigger the destruction of the current instance and a creation of a new instance of the analyzer.

Interesting bug! To fix, please:
1) check if `framelist` is empty before calling `.begin()` on it, or prevent that case from ever happening.
2) make sure all data members involved in the decoding process are cleared at the top of the worker thread.

Don't worry about the results, that gets reset on every run in `SENTAnalyzer::SetupResults` and you don't have to worry about the simulation data generator, because it's impossible for a single instance of an analyzer to produce more than 1 simulated capture. And of course `SENTAnalyzerSettings` actually should maintain state through the life of the analyzer instance.

**Comment by bavovanachte** [comment]
@Marcus10110 Thanks a lot!
Wasn't aware of the GDB option, should have read the articles more carefully. Sorry about that. 

@brmurdock I will try to make this fix today or tomorrow, and let you know.

**Comment by bavovanachte** [comment]
@brmurdock Fix in https://github.com/melexis/SENTAnalyzer/pull/11.

**Comment by bavovanachte** [comment]
@brmurdock Can you check if this fixes the issue for you, and close the ticket if it does?

**Comment by brmurdock** [comment]
This does in fact seem to fix the issue. Thank you.
